import '../styles/w3css/index.css'

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.jpeg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        {children}
      </body>
    </html>
  );
}
